id = "asciidoc"
name = "AsciiDoc"
version = "0.5.0"
schema_version = 1
authors = ["Dunya Kirkali <dunyakirkali@gmail.com>"]
description = "Support for AsciiDoc syntax"
repository = "https://github.com/dunyakirkali/zed-asciidoc"
snippets = "./snippets/asciidoc.json"

[grammars.asciidoc_inline]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
commit = "8b7488e4a92133c9adacc49e97652007e1b6621a"
path = "tree-sitter-asciidoc_inline"

[grammars.asciidoc]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
commit = "8b7488e4a92133c9adacc49e97652007e1b6621a"
path = "tree-sitter-asciidoc"
